package com.justanotherdeveloper.totalslite

const val USERS_PATH = "users"
const val PHONE_NUMBER_PATH = "phone_number"
const val PROFILE_PHOTO_URL_PATH ="profile_photo_url"
const val PROFILE_BIO_PATH = "profile_bio"
const val USERNAME_PATH = "username"
const val USER_ID_PATH = "user_id"
const val NAME_PATH = "name"
const val DATE_JOINED_PATH = "date_joined"
const val BIRTHDAY_PATH = "birthday"
const val BLOCKED_USERS_PATH = "blocked_users"
const val BANNED_PATH = "banned"

const val GOALS_PATH = "goals"
const val AMOUNT_PATH = "amount"
const val TITLE_PATH = "title"
const val TIMESTAMP_ADDED_PATH = "timestamp_added"
const val TIMESTAMP_UPDATED_PATH = "timestamp_updated"
const val TIMESTAMP_GOAL_DATE_PATH = "timestamp_goal_date"
const val GOAL_TIME_PATH = "goal_time"
const val REPEATING_DAYS_PATH = "repeating_days"
const val NOTES_PATH = "notes"
const val LINKS_PATH = "links"
const val LABELS_PATH = "labels"
const val IS_ACTIVE_PATH = "is_active"
const val ACTIVE_START_TIMESTAMP_PATH = "active_start_timestamp"

const val POSTS_PATH = "posts"
const val ORIGINAL_AMOUNT_PATH = "original_amount"
const val POST_IS_LAST_OF_DUE_DATE_PATH = "post_is_last_of_due_date"
const val TIMESTAMP_POSTED_PATH = "timestamp_posted"
const val GOAL_FIREBASE_KEY_PATH = "goal_firebase_key"
const val TIMESTAMP_DUE_DATE_PATH = "timestamp_due_date"
const val PHOTO_URL_PATH = "photo_url"
const val CAPTION_PATH = "caption"
const val IS_INCOMPLETE_PATH = "is_incomplete"
const val NOT_REQUIRED_PATH = "not_required"
const val LIKES_PATH = "likes"
const val SEEN_LIKES_PATH = "seen_likes"
const val REPORTED_PATH = "reported"
const val REASON_REPORTED_PATH = "reason_reported"
const val REPORT_RESOLVED_PATH = "report_resolved"
const val RESOLVED_REPORT_NOTE_PATH = "resolved_report_note"
const val DELETED_POST_NOTICE_SEEN_PATH = "deleted_post_notice_seen"

const val PROFILES_PATH = "profiles"
const val PROFILE_LABEL_PATH = "profile_label"
const val TOTALS_START_DATE_PATH = "totals_start_date"

const val PHOTOS_LOCATION = "photos"
const val PROFILE_PHOTOS_LOCATION = "profile_photos"